update release_pr workflow

diff --git a/.github/workflows/release_pr.yml b/.github/workflows/release_pr.yml
--- a/.github/workflows/release_pr.yml
+++ b/.github/workflows/release_pr.yml
@@ -57,4 +57,6 @@ jobs:
 
       - name: Fail if no docs changes
         if: ${{ steps.changes.outputs.docs == 'false' }}
-        run: exit 1
+        run: |
+          echo "::error::Documentation should be updated when version is changed."
+          exit 1
